version: "3.3"
services:
  web:
    build: .
    ports:
      - "80:4000"
    logging:
      driver: gcplogs
        max-size: "200k"
    volumes:
      - .:/code
  redis:
    image: "redis:alpine"
    logging:
      driver: gcplogs
