version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:4000"
    logging:
      driver: "json-file"
      options: 
        max-size: "200k"
    volumes:
      - .:/code
    image: msilv204/tcmg412_restful_redis
  redis:
    image: "redis:alpine"
